### ISSUE TITLE
Bug-Report 插件发生了错误（小白不知道是什么错😳）

### ISSUE THREAD

**Issue by jierme** [beansoft/iscratch-support#49]
---

## What happened

(please describe what you were doing when this exception occurred)
Just try to take notes for LaTeX.

## Version information

PyCharm `2023.1.1` • Notes plugin `com.github.beansoft.iscratch 2023.1.3`
## Exception

null

```
com.intellij.diagnostic.PluginException: Cannot init toolwindow com.github.beansoft.iscratch.ui.CodePaneToolWindowFactory@10ff2547 [Plugin: com.github.beansoft.iscratch]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:188)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.util.regex.PatternSyntaxException: Unclosed group near index 66
/Users/dian/Downloads/LaTeX/01：LaTeX教程/01：LaTeX学习视频(texlive）/Learn
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.accept(Pattern.java:1878)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:3053)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2124)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.lang.String.replaceAll(String.java:2940)
	at com.github.beansoft.iscratch.utils.NotePathUtil.guessShortPath(NotePathUtil.java:33)
	at com.github.beansoft.iscratch.ui.list.BaseIconCellRenderer.appendUrl(BaseIconCellRenderer.java:129)
	at com.github.beansoft.iscratch.ui.list.NoteListCellRenderer.customizeCellRenderer(NoteListCellRenderer.java:121)
	at com.github.beansoft.iscratch.ui.list.NoteListCellRenderer.getListCellRendererComponent(NoteListCellRenderer.java:99)
	at com.github.beansoft.iscratch.ui.list.MultilineListCellRenderer.getListCellRendererComponent(MultilineListCellRenderer.java:47)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at com.github.beansoft.iscratch.ui.list.CodeListUtil.trySelectFirst(CodeListUtil.java:22)
	at com.github.beansoft.iscratch.ui.ScratchCodePane.valueChanged(ScratchCodePane.java:1646)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:3021)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3522)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:650)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:656)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1120)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:306)
	at java.desktop/javax.swing.JTree.setSelectionPaths(JTree.java:1723)
	at java.desktop/javax.swing.JTree.setSelectionRows(JTree.java:1806)
	at java.desktop/javax.swing.JTree.setSelectionRow(JTree.java:1781)
	at com.intellij.util.ui.tree.TreeUtil.lambda$showAndSelect$9(TreeUtil.java:627)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:676)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:584)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:580)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:505)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:1016)
	at com.github.beansoft.iscratch.ui.tree.CodeTreeUtil.selectFolder(CodeTreeUtil.java:112)
	at com.github.beansoft.iscratch.ui.ScratchCodePane.restoreTreeListState(ScratchCodePane.java:1782)
	at com.github.beansoft.iscratch.ui.ScratchCodePane.restoreExpandedPaths(ScratchCodePane.java:758)
	at com.github.beansoft.iscratch.ui.ScratchCodePane.smartExpandTree(ScratchCodePane.java:695)
	at com.github.beansoft.iscratch.ui.ScratchCodePane.<init>(ScratchCodePane.java:370)
	at com.github.beansoft.iscratch.ui.CodePaneToolWindowFactory.createToolWindowContent(CodePaneToolWindowFactory.kt:73)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:548)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:527)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:983)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:920)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:906)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1094)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:176)
	... 39 more
```

**Comment by jierme** [comment]
之后这个插件就再也无法正常显示了。

![CleanShot 2023-05-06 at 16 28 45](https://user-images.githubusercontent.com/57268924/236612932-e6cf0dce-1b0f-4dc7-941b-c624d9f03417.png)

**Comment by beansoft** [comment]
你好，可能是路径里的括号被当做了正则表达式，能否将 notes.db 私信发到我的邮件里看看有没有办法先手工处理一下。 beansoft@126.com

**Comment by jierme** [comment]
> 你好，可能是路径里的括号被当做了正则表达式，能否将 notes.db 私信发到我的邮件里看看有没有办法先手工处理一下。 [beansoft@126.com](mailto:beansoft@126.com)

无需帮我修复，当前这个库是新建的，除了刚新增的 LaTeX 没有其它重要资料。如果你需要用来维护插件，我一会儿发给作者~
