### ISSUE TITLE
2023.1.1插件报错

### ISSUE THREAD

**Issue by custsly** [beansoft/iscratch-support#51]
## What happened

表现为代码前面出现两个Notes的笔记标识, 删除之后还剩一个, 重启 IDEA 之后弹出报错信息, bug-report如下

## Version information

IntelliJ IDEA `2023.1.1` • Notes plugin `com.github.beansoft.iscratch 2023.1.3`
## Exception

null

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
	at com.github.beansoft.iscratch.highlight.BookmarksManager.refreshAllRenderer(BookmarksManager.kt:289)
	at com.github.beansoft.iscratch.highlight.BookmarksManager$Companion.refreshAllProjectsGutter$lambda$3$lambda$2(BookmarksManager.kt:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.beansoft.iscratch.highlight.BookmarksManager$Companion.refreshAllProjectsGutter$lambda$3(BookmarksManager.kt:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by beansoft** [comment]
感谢反馈，能否提供下notes.db文件私信发过来 beansoft@126.com

**Comment by custsly** [comment]
已发送, 请查收
