### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ghost** [beansoft/iscratch-support#52]
Please file this bug report at https://github.com/beansoft/iscratch-support/issues/new.

---

## What happened

 just  take notes

## Version information

IntelliJ IDEA `2023.1.2` • Notes plugin `com.github.beansoft.iscratch 2023.1.3`
## Exception

null

```
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:783)
	at com.github.beansoft.iscratch.highlight.BookmarksManager.refreshAllRenderer(BookmarksManager.kt:289)
	at com.github.beansoft.iscratch.highlight.BookmarksManager$Companion.refreshAllProjectsGutter$lambda$3$lambda$2(BookmarksManager.kt:62)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.beansoft.iscratch.highlight.BookmarksManager$Companion.refreshAllProjectsGutter$lambda$3(BookmarksManager.kt:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by beansoft** [comment]
[Notes.zip](https://github.com/beansoft/iscratch-support/files/11544334/Notes.zip)
Please try whether this test version fixed your problem or not.
请尝试此测试版本是否修复了你的问题，感谢。
