### ISSUE TITLE
iScratch is not a directory

### ISSUE THREAD

**Issue by mitra-shan** [beansoft/iscratch-support#9]
Hi Beansoft team, just installed the Notes plugin to my Webstorm but, getting the issue of iScratch is not a directory. I believe it's coming from some system notification service and the com.github.com.beansoft.idea.ideascratch package does not exist. Can you please suggest some fix. Thanks in advance.

**Comment by beansoft** [comment]
Hi, try https://plugins.jetbrains.com/plugin/17501-notes/versions download and install from disk. Also i'd know your WebStorm version and operation system, and is your system user is admin or not.

1. Open your IDE and press Ctrl+Alt+S to open the IDE settings.
2. Select Plugins, click  and then click Install Plugin from Disk.
3. Select the plugin archive file and click OK.
4. Click OK to apply the changes and restart your IDE if prompted.

**Comment by mitra-shan** [comment]
Hi Team, thanks for your prompt response I do really appreciate it. Unfortunately this option is also failing. I'm using 
- Mac ( Intel Processor )
- Webstorm 2021.3 and the latest stable of Notes ( https://plugins.jetbrains.com/plugin/download?rel=true&updateId=159582 ) still getting the issue and more importantly this - `iScratch is not a directory` is looping infinitely to hang the Webstorm with heavy memory leak.
- Yes, I'm the system admin

Thanks once again for your support.

**Comment by beansoft** [comment]
Hi mitra, I need your help to fix this issue since two other user reported similiar issue in Mac or Windows, but i cant reproduce it. Would you mind to upload the log file here? To locate the log file, choose the menu of your WebStorm,  Help | Show Log in Finder/Explorer action. Thanks a lot!

**Comment by mitra-shan** [comment]
Hi Team, the log is huge ( 10 mb ) but, Notes related issues are the below lines. I'm sure you will get some clue - these lines are actually repeating indefinitely so log is getting huge. Please let me know if this helps -

>|
2022-04-08 17:25:14,849 [ 437319]   INFO -                         STDERR - java.io.IOException: Not a directory 
2022-04-08 17:25:14,849 [ 437319]   INFO -                         STDERR - 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method) 
2022-04-08 17:25:14,849 [ 437319]   INFO -                         STDERR - 	at java.base/java.io.File.createNewFile(File.java:1035) 
2022-04-08 17:25:14,850 [ 437320]   INFO -                         STDERR - 	at com.github.beansoft.iscratch.dao.SQLiteConnector.getConnection(SQLiteConnector.java:22) 
2022-04-08 17:25:14,850 [ 437320]   INFO -                         STDERR - 	at com.github.beansoft.iscratch.service.FavoriteDataService.getConnection(FavoriteDataService.java:66) 
2022-04-08 17:25:14,850 [ 437320]   INFO -                         STDERR - 	at com.github.beansoft.iscratch.service.FavoriteDataService.getFavoriteLeafDao(FavoriteDataService.java:96) 
2022-04-08 17:25:14,850 [ 437320]   INFO -                         STDERR - 	at com.github.beansoft.iscratch.service.FavoriteDataService.getCodesByPathAndLine(FavoriteDataService.java:301) 
2022-04-08 17:25:14,850 [ 437320]   INFO -                         STDERR - 	at com.github.beansoft.iscratch.highlight.CodeNotesEditorLinePainter.getLineExtensions(CodeNotesEditorLinePainter.java:88) 


Also for your reference I'm sharing my SQLITE db snap where no tables are getting created so might be this could be issue of driver and SQLIte connection. In case this helps you to understand better.
<img width="364" alt="note-db-sync" src="https://user-images.githubusercontent.com/9672011/162435356-277f913a-ad52-4267-9f30-feb4d21a76cc.png">

**Comment by beansoft** [comment]
This do helps me a lot! I'll take a look at the reason.

**Comment by beansoft** [comment]
I've found the reason, the directory in the settings for database might not exists. But at first I've fix the issue that not hang the Webstorm anymore and give user the reason why it fails. Plz have a try first by download and install it:

https://plugins.jetbrains.com/plugin/download?rel=true&updateId=166919

**Comment by mitra-shan** [comment]
Hi Mate, this is awesome. I have tested it and the db is also getting created and data is getting stored. So the memory leak issue is not there now. Let me play with it more to tell you about any further challenges. I'm waiting for the Evernote integration as I have created my dev token but, I think you are still working on the authentication and evernote integration.

**Comment by beansoft** [comment]
The Evernote ingetration so far only supports store and read codes only, I'm still working on how to view or edit the Evernote content(in fact it's something HTML like).
